export default {
  CREATE_EVENT: 'EVENTS/CREATE_EVENT',
  FETCH_HOSTED_EVENTS_SUCCESS: 'EVENTS/FETCH_HOSTED_EVENTS_SUCCESS',
  REQUEST_END: 'EVENTS/REQUEST_END',
  REQUEST_START: 'EVENTS/REQUEST_START',
};